exports.initProducts = (company_id) => [
     {
          name: "Men Gentle Shoes",
          category_id: 2,
          uom_name: 1,
          published: true,
          qty: "1.0",
          list_price: "100.00",
          public_categ_id: 2,
          company_id,
          description: "this is a scam",
          standard_price: "269",
          images: [
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
          ],
     },
     {
          name: "Porto White Cap",
          category_id: 2,
          uom_name: 1,
          published: true,
          qty: "1.0",
          list_price: "100.00",
          public_categ_id: 2,
          company_id,
          description: "this is a scam",
          standard_price: "101",
          images: [
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
          ],
     },
     {
          name: "Winter Towel",
          category_id: 2,
          uom_name: 1,
          published: true,
          qty: "1.0",
          list_price: "100.00",
          public_categ_id: 2,
          company_id,
          description: "this is a scam",
          standard_price: "1280",
          images: [
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
          ],
     },
     {
          name: "Product Extended",
          category_id: 2,
          uom_name: 1,
          published: true,
          qty: "1.0",
          list_price: "100.00",
          public_categ_id: 2,
          company_id,
          description: "this is a scam",
          standard_price: "1280",
          images: [
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-5.jpg",
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
          ],
     },
     {
          name: "Sports Shoes",
          category_id: 2,
          uom_name: 1,
          published: true,
          qty: "1.0",
          list_price: "100.00",
          public_categ_id: 2,
          company_id,
          description: "this is a scam",
          standard_price: "299",
          images: [
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-6.jpg",
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
          ],
     },
     {
          name: "Women Bag",
          category_id: 2,
          uom_name: 1,
          published: true,
          qty: "1.0",
          list_price: "100.00",
          public_categ_id: 2,
          company_id,
          description: "this is a scam",
          standard_price: "1280",
          images: [
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-7.jpg",
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
          ],
     },
     {
          name: "Men Black Belts",
          category_id: 2,
          uom_name: 1,
          published: true,
          qty: "1.0",
          list_price: "100.00",
          public_categ_id: 2,
          company_id,
          description: "this is a scam",
          standard_price: "55",
          images: [
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-8.jpg",
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
          ],
     },
     {
          name: "Women Bag",
          category_id: 2,
          uom_name: 1,
          published: true,
          qty: "1.0",
          list_price: "100.00",
          public_categ_id: 2,
          company_id,
          description: "this is a scam",
          standard_price: "199",
          images: [
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-9.jpg",
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
          ],
     },
     {
          name: "Product Short Name",
          category_id: 2,
          uom_name: 1,
          published: true,
          qty: "1.0",
          list_price: "100.00",
          public_categ_id: 2,
          company_id,
          description: "this is a scam",
          standard_price: "39",
          images: [
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-14.jpg",
               "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
          ],
     },
];
