exports.initProducts = (company_id, categ_ids) => {
     const ProductByCateg = {
          "Books and Media": {
               products: [
                    {
                         name: "1984",
                         category_id: "2",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "Books and Media",
                         description:
                              "A dystopian social science fiction novel and cautionary tale, written by the English writer George Orwell.",
                         qty: 40,
                         weight: "1kg",
                         size: "0.5kg",

                         dimension: "3",
                         standard_price: "500",
                         discount: {
                              amount: "200",
                              type: "",
                              start_date: "12/10/2024",
                              end_date: "12/10/2025",
                              discountedAmount: "300",
                         },
                         company_id,
                         product_tag_ids: ["123"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 39,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "To Kill a Mockingbird",
                         category_id: "2",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "Books and Media",
                         description:
                              "A novel by Harper Lee published in 1960. Instantly successful, widely read in high schools and middle schools in the United States.",
                         qty: 40,
                         weight: "1kg",
                         size: "0.5kg",
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                         dimension: "3",
                         standard_price: "500",
                         discount: {
                              amount: "200",
                              type: "",
                              start_date: "12/10/2024",
                              end_date: "12/10/2025",
                              discountedAmount: "300",
                         },
                         company_id,
                         product_tag_ids: ["123"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 39,
                         x_inventory_tracking: true,
                    },
                    {
                         name: "The Great Gatsby",
                         category_id: "2",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "Books and Media",
                         description:
                              "A 1925 novel written by American author F. Scott Fitzgerald that follows a cast of characters living in the fictional towns of West Egg and East Egg.",
                         qty: 40,
                         weight: "1kg",
                         size: "0.5kg",
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                         dimension: "3",
                         standard_price: "500",
                         discount: {
                              amount: "200",
                              type: "",
                              start_date: "12/10/2024",
                              end_date: "12/10/2025",
                              discountedAmount: "300",
                         },
                         company_id,
                         product_tag_ids: ["123"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 39,
                         x_inventory_tracking: true,
                    },
                    {
                         name: "Pride and Prejudice",
                         category_id: "2",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "Books and Media",
                         description: "A romantic novel of manners written by Jane Austen in 1813.",
                         qty: 40,
                         weight: "1kg",
                         size: "0.5kg",
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                         dimension: "3",
                         standard_price: "500",
                         discount: {
                              amount: "200",
                              type: "",
                              start_date: "12/10/2024",
                              end_date: "12/10/2025",
                              discountedAmount: "300",
                         },
                         company_id,
                         product_tag_ids: ["123"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 39,
                         x_inventory_tracking: true,
                    },
                    {
                         name: "The Catcher in the Rye",
                         category_id: "2",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "Books and Media",
                         description:
                              "A novel by J. D. Salinger, partially published in serial form in 1945–1946 and as a novel in 1951.",
                         qty: 40,
                         weight: "1kg",
                         size: "0.5kg",
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                         dimension: "3",
                         standard_price: "500",
                         discount: {
                              amount: "200",
                              type: "",
                              start_date: "12/10/2024",
                              end_date: "12/10/2025",
                              discountedAmount: "300",
                         },
                         company_id,
                         product_tag_ids: ["123"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 39,
                         x_inventory_tracking: true,
                    },
                    {
                         name: "Moby-Dick",
                         category_id: "2",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "Books and Media",
                         description:
                              "An 1851 novel by Herman Melville. The book is the sailor Ishmael’s narrative of the obsessive quest of Ahab, captain of the whaling ship Pequod.",
                         qty: 40,
                         weight: "1kg",
                         size: "0.5kg",
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                         dimension: "3",
                         standard_price: "500",
                         discount: {
                              amount: "200",
                              type: "",
                              start_date: "12/10/2024",
                              end_date: "12/10/2025",
                              discountedAmount: "300",
                         },
                         company_id,
                         product_tag_ids: ["123"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 39,
                         x_inventory_tracking: true,
                    },
               ],
               categories: [{ name: "fiction" }, { name: "thriller" }, { name: "romance" }],
          },
          Electronics: {
               products: [
                    {
                         name: "Smartphone XYZ",
                         category_id: "254",
                         uom_name: "1",
                         published: true,
                         list_price: "500.00",
                         public_categ: "Electronics",
                         description: "A high-end smartphone with all the latest features.",
                         qty: 100,
                         weight: "0.5kg",
                         size: "0.2kg",
                         dimension: "10",
                         standard_price: "450",
                         discount: {
                              amount: "50",
                              type: "percentage",
                              start_date: "01/01/2024",
                              end_date: "01/01/2025",
                              discountedAmount: "450",
                         },
                         company_id,
                         product_tag_ids: ["456"],
                         x_variants: true,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 90,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Laptop ABC",
                         category_id: "254",
                         uom_name: "1",
                         published: true,
                         list_price: "1200.00",
                         public_categ: "Electronics",
                         description:
                              "A high-performance laptop suitable for all your computing needs.",
                         qty: 50,
                         weight: "1.5kg",
                         size: "1.0kg",
                         dimension: "15",
                         standard_price: "1100",
                         discount: {
                              amount: "100",
                              type: "flat",
                              start_date: "02/01/2024",
                              end_date: "02/01/2025",
                              discountedAmount: "1100",
                         },
                         company_id,
                         product_tag_ids: ["789"],
                         x_variants: true,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 45,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "smartphones" }, { name: "laptops" }, { name: "accessories" }],
          },
          Clothing: {
               products: [
                    {
                         name: "T-Shirt ABC",
                         category_id: "255",
                         uom_name: "1",
                         published: true,
                         list_price: "25.00",
                         public_categ: "Clothing",
                         description: "A comfortable cotton t-shirt available in various sizes.",
                         qty: 200,
                         weight: "0.2kg",
                         size: "0.1kg",
                         dimension: "2",
                         standard_price: "20",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "05/01/2024",
                              end_date: "05/01/2025",
                              discountedAmount: "20",
                         },
                         company_id,
                         product_tag_ids: ["789"],
                         x_variants: true,
                         free_shipping: false,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 180,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Jeans XYZ",
                         category_id: "255",
                         uom_name: "1",
                         published: true,
                         list_price: "50.00",
                         public_categ: "Clothing",
                         description: "Stylish jeans for everyday wear.",
                         qty: 150,
                         weight: "0.5kg",
                         size: "0.4kg",
                         dimension: "5",
                         standard_price: "45",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "06/01/2024",
                              end_date: "06/01/2025",
                              discountedAmount: "45",
                         },
                         company_id,
                         product_tag_ids: ["654"],
                         x_variants: true,
                         free_shipping: false,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 140,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "men" }, { name: "women" }, { name: "kids" }],
          },
          "Home and Kitchen": {
               products: [
                    {
                         name: "Blender",
                         category_id: "256",
                         uom_name: "1",
                         published: true,
                         list_price: "150.00",
                         public_categ: "Home and Kitchen",
                         description: "A powerful blender for all your kitchen needs.",
                         qty: 50,
                         weight: "2kg",
                         size: "1.5kg",
                         dimension: "15",
                         standard_price: "140",
                         discount: {
                              amount: "10",
                              type: "flat",
                              start_date: "01/03/2024",
                              end_date: "01/03/2025",
                              discountedAmount: "140",
                         },
                         company_id,
                         product_tag_ids: ["987"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 45,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Microwave Oven",
                         category_id: "256",
                         uom_name: "1",
                         published: true,
                         list_price: "200.00",
                         public_categ: "Home and Kitchen",
                         description: "A high-efficiency microwave oven.",
                         qty: 40,
                         weight: "10kg",
                         size: "8kg",
                         dimension: "20",
                         standard_price: "190",
                         discount: {
                              amount: "10",
                              type: "flat",
                              start_date: "02/03/2024",
                              end_date: "02/03/2025",
                              discountedAmount: "190",
                         },
                         company_id,
                         product_tag_ids: ["654"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 35,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "appliances" }, { name: "cookware" }, { name: "utensils" }],
          },
          "Health and Beauty": {
               products: [
                    {
                         name: "Face Cream",
                         category_id: "257",
                         uom_name: "1",
                         published: true,
                         list_price: "60.00",
                         public_categ: "Health and Beauty",
                         description: "A hydrating face cream for all skin types.",
                         qty: 150,
                         weight: "0.1kg",
                         size: "0.05kg",
                         dimension: "5",
                         standard_price: "55",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "06/01/2024",
                              end_date: "06/01/2025",
                              discountedAmount: "55",
                         },
                         company_id,
                         product_tag_ids: ["654"],
                         x_variants: false,
                         free_shipping: false,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 145,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Shampoo",
                         category_id: "257",
                         uom_name: "1",
                         published: true,
                         list_price: "30.00",
                         public_categ: "Health and Beauty",
                         description: "A nourishing shampoo for healthy hair.",
                         qty: 120,
                         weight: "0.3kg",
                         size: "0.2kg",
                         dimension: "3",
                         standard_price: "25",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "07/01/2024",
                              end_date: "07/01/2025",
                              discountedAmount: "25",
                         },
                         company_id,
                         product_tag_ids: ["987"],
                         x_variants: false,
                         free_shipping: false,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 115,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "skincare" }, { name: "haircare" }, { name: "makeup" }],
          },
          "Sports and Outdoors": {
               products: [
                    {
                         name: "Running Shoes",
                         category_id: "258",
                         uom_name: "1",
                         published: true,
                         list_price: "120.00",
                         public_categ: "Sports and Outdoors",
                         description: "Lightweight and comfortable running shoes.",
                         qty: 80,
                         weight: "0.8kg",
                         size: "0.6kg",
                         dimension: "8",
                         standard_price: "110",
                         discount: {
                              amount: "10",
                              type: "flat",
                              start_date: "04/01/2024",
                              end_date: "04/01/2025",
                              discountedAmount: "110",
                         },
                         company_id,
                         product_tag_ids: ["321"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 75,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Basketball",
                         category_id: "258",
                         uom_name: "1",
                         published: true,
                         list_price: "40.00",
                         public_categ: "Sports and Outdoors",
                         description:
                              "A high-quality basketball for professional and recreational use.",
                         qty: 150,
                         weight: "0.6kg",
                         size: "0.5kg",
                         dimension: "6",
                         standard_price: "35",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "05/01/2024",
                              end_date: "05/01/2025",
                              discountedAmount: "35",
                         },
                         company_id,
                         product_tag_ids: ["987"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 145,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "footwear" }, { name: "equipment" }, { name: "apparel" }],
          },
          "Toys and Games": {
               products: [
                    {
                         name: "Lego Set",
                         category_id: "259",
                         uom_name: "1",
                         published: true,
                         list_price: "75.00",
                         public_categ: "Toys and Games",
                         description: "A fun and educational Lego set for kids.",
                         qty: 200,
                         weight: "1.0kg",
                         size: "0.8kg",
                         dimension: "10",
                         standard_price: "70",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "01/04/2024",
                              end_date: "01/04/2025",
                              discountedAmount: "70",
                         },
                         company_id,
                         product_tag_ids: ["321"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 190,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Board Game",
                         category_id: "259",
                         uom_name: "1",
                         published: true,
                         list_price: "50.00",
                         public_categ: "Toys and Games",
                         description: "An exciting board game for the whole family.",
                         qty: 150,
                         weight: "0.5kg",
                         size: "0.4kg",
                         dimension: "5",
                         standard_price: "45",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "02/04/2024",
                              end_date: "02/04/2025",
                              discountedAmount: "45",
                         },
                         company_id,
                         product_tag_ids: ["987"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 145,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "building" }, { name: "board games" }, { name: "educational" }],
          },
          Automotive: {
               products: [
                    {
                         name: "Car Battery",
                         category_id: "261",
                         uom_name: "1",
                         published: true,
                         list_price: "150.00",
                         public_categ: "Automotive",
                         description: "A durable car battery with long life.",
                         qty: 100,
                         weight: "10kg",
                         size: "8kg",
                         dimension: "20",
                         standard_price: "140",
                         discount: {
                              amount: "10",
                              type: "flat",
                              start_date: "01/05/2024",
                              end_date: "01/05/2025",
                              discountedAmount: "140",
                         },
                         company_id,
                         product_tag_ids: ["321"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 90,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Engine Oil",
                         category_id: "261",
                         uom_name: "1",
                         published: true,
                         list_price: "40.00",
                         public_categ: "Automotive",
                         description: "High-quality engine oil for all types of vehicles.",
                         qty: 200,
                         weight: "1kg",
                         size: "0.8kg",
                         dimension: "10",
                         standard_price: "35",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "02/05/2024",
                              end_date: "02/05/2025",
                              discountedAmount: "35",
                         },
                         company_id,
                         product_tag_ids: ["654"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 190,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "batteries" }, { name: "oils" }, { name: "accessories" }],
          },
          Furniture: {
               products: [
                    {
                         name: "Sofa",
                         category_id: "262",
                         uom_name: "1",
                         published: true,
                         list_price: "500.00",
                         public_categ: "Furniture",
                         description: "A comfortable and stylish sofa.",
                         qty: 30,
                         weight: "30kg",
                         size: "25kg",
                         dimension: "50",
                         standard_price: "450",
                         discount: {
                              amount: "50",
                              type: "flat",
                              start_date: "01/06/2024",
                              end_date: "01/06/2025",
                              discountedAmount: "450",
                         },
                         company_id,
                         product_tag_ids: ["987"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 28,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Dining Table",
                         category_id: "262",
                         uom_name: "1",
                         published: true,
                         list_price: "300.00",
                         public_categ: "Furniture",
                         description: "A modern dining table that seats six.",
                         qty: 20,
                         weight: "20kg",
                         size: "18kg",
                         dimension: "40",
                         standard_price: "280",
                         discount: {
                              amount: "20",
                              type: "flat",
                              start_date: "02/06/2024",
                              end_date: "02/06/2025",
                              discountedAmount: "280",
                         },
                         company_id,
                         product_tag_ids: ["321"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 18,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "living room" }, { name: "dining room" }, { name: "bedroom" }],
          },
          "Jewelry and Accessories": {
               products: [
                    {
                         name: "Gold Necklace",
                         category_id: "263",
                         uom_name: "1",
                         published: true,
                         list_price: "1000.00",
                         public_categ: "Jewelry and Accessories",
                         description: "A beautiful gold necklace.",
                         qty: 50,
                         weight: "0.05kg",
                         size: "0.02kg",
                         dimension: "5",
                         standard_price: "950",
                         discount: {
                              amount: "50",
                              type: "flat",
                              start_date: "01/07/2024",
                              end_date: "01/07/2025",
                              discountedAmount: "950",
                         },
                         company_id,
                         product_tag_ids: ["987"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 48,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Silver Bracelet",
                         category_id: "263",
                         uom_name: "1",
                         published: true,
                         list_price: "500.00",
                         public_categ: "Jewelry and Accessories",
                         description: "An elegant silver bracelet.",
                         qty: 100,
                         weight: "0.03kg",
                         size: "0.01kg",
                         dimension: "3",
                         standard_price: "450",
                         discount: {
                              amount: "50",
                              type: "flat",
                              start_date: "02/07/2024",
                              end_date: "02/07/2025",
                              discountedAmount: "450",
                         },
                         company_id,
                         product_tag_ids: ["654"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 95,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "necklaces" }, { name: "bracelets" }, { name: "earrings" }],
          },
          "Pet Supplies": {
               products: [
                    {
                         name: "Dog Food",
                         category_id: "264",
                         uom_name: "1",
                         published: true,
                         list_price: "50.00",
                         public_categ: "Pet Supplies",
                         description: "Nutritious dog food for your pet.",
                         qty: 200,
                         weight: "2kg",
                         size: "1.5kg",
                         dimension: "10",
                         standard_price: "45",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "01/08/2024",
                              end_date: "01/08/2025",
                              discountedAmount: "45",
                         },
                         company_id,
                         product_tag_ids: ["321"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 190,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Cat Litter",
                         category_id: "264",
                         uom_name: "1",
                         published: true,
                         list_price: "30.00",
                         public_categ: "Pet Supplies",
                         description: "Clumping cat litter for easy cleaning.",
                         qty: 150,
                         weight: "5kg",
                         size: "4.5kg",
                         dimension: "15",
                         standard_price: "25",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "02/08/2024",
                              end_date: "02/08/2025",
                              discountedAmount: "25",
                         },
                         company_id,
                         product_tag_ids: ["654"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 140,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "food" }, { name: "litter" }, { name: "toys" }],
          },
          "Baby and Maternity": {
               products: [
                    {
                         name: "Baby Stroller",
                         category_id: "265",
                         uom_name: "1",
                         published: true,
                         list_price: "200.00",
                         public_categ: "Baby and Maternity",
                         description: "A comfortable and safe stroller for your baby.",
                         qty: 50,
                         weight: "10kg",
                         size: "8kg",
                         dimension: "20",
                         standard_price: "190",
                         discount: {
                              amount: "10",
                              type: "flat",
                              start_date: "01/09/2024",
                              end_date: "01/09/2025",
                              discountedAmount: "190",
                         },
                         company_id,
                         product_tag_ids: ["321"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 45,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Maternity Dress",
                         category_id: "265",
                         uom_name: "1",
                         published: true,
                         list_price: "60.00",
                         public_categ: "Baby and Maternity",
                         description: "A stylish and comfortable maternity dress.",
                         qty: 100,
                         weight: "0.5kg",
                         size: "0.4kg",
                         dimension: "5",
                         standard_price: "55",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "02/09/2024",
                              end_date: "02/09/2025",
                              discountedAmount: "55",
                         },
                         company_id,
                         product_tag_ids: ["654"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 95,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "strollers" }, { name: "clothing" }, { name: "toys" }],
          },
          "Groceries and Food": {
               products: [
                    {
                         name: "Organic Apples",
                         category_id: "266",
                         uom_name: "1",
                         published: true,
                         list_price: "5.00",
                         public_categ: "Groceries and Food",
                         description: "Fresh organic apples.",
                         qty: 200,
                         weight: "1kg",
                         size: "0.8kg",
                         dimension: "5",
                         standard_price: "4.50",
                         discount: {
                              amount: "0.50",
                              type: "flat",
                              start_date: "01/10/2024",
                              end_date: "01/10/2025",
                              discountedAmount: "4.50",
                         },
                         company_id,
                         product_tag_ids: ["321"],
                         x_variants: false,
                         free_shipping: false,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 190,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Almond Milk",
                         category_id: "266",
                         uom_name: "1",
                         published: true,
                         list_price: "3.00",
                         public_categ: "Groceries and Food",
                         description: "Healthy and delicious almond milk.",
                         qty: 150,
                         weight: "1kg",
                         size: "0.9kg",
                         dimension: "5",
                         standard_price: "2.75",
                         discount: {
                              amount: "0.25",
                              type: "flat",
                              start_date: "02/10/2024",
                              end_date: "02/10/2025",
                              discountedAmount: "2.75",
                         },
                         company_id,
                         product_tag_ids: ["654"],
                         x_variants: false,
                         free_shipping: false,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 145,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "fruits" }, { name: "beverages" }, { name: "snacks" }],
          },
          "Tools and Home Improvement": {
               products: [
                    {
                         name: "Electric Drill",
                         category_id: "267",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "tools_home_improvement",
                         description: "A powerful electric drill for home improvement projects.",
                         qty: 50,
                         weight: "2kg",
                         size: "1.5kg",
                         dimension: "10",
                         standard_price: "90",
                         discount: {
                              amount: "10",
                              type: "flat",
                              start_date: "01/11/2024",
                              end_date: "01/11/2025",
                              discountedAmount: "90",
                         },
                         company_id,
                         product_tag_ids: ["321"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 45,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Hammer",
                         category_id: "267",
                         uom_name: "1",
                         published: true,
                         list_price: "15.00",
                         public_categ: "tools_home_improvement",
                         description: "A durable hammer for all your home improvement needs.",
                         qty: 100,
                         weight: "0.5kg",
                         size: "0.4kg",
                         dimension: "5",
                         standard_price: "13",
                         discount: {
                              amount: "2",
                              type: "flat",
                              start_date: "02/11/2024",
                              end_date: "02/11/2025",
                              discountedAmount: "13",
                         },
                         company_id,
                         product_tag_ids: ["654"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 95,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "power tools" }, { name: "hand tools" }, { name: "hardware" }],
          },
          "Office Supplies": {
               products: [
                    {
                         name: "Printer",
                         category_id: "268",
                         uom_name: "1",
                         published: true,
                         list_price: "150.00",
                         public_categ: "Office Supplies",
                         description: "A high-quality printer for your office needs.",
                         qty: 30,
                         weight: "5kg",
                         size: "4kg",
                         dimension: "15",
                         standard_price: "140",
                         discount: {
                              amount: "10",
                              type: "flat",
                              start_date: "01/12/2024",
                              end_date: "01/12/2025",
                              discountedAmount: "140",
                         },
                         company_id,
                         product_tag_ids: ["321"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 28,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Office Chair",
                         category_id: "268",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "Office Supplies",
                         description: "A comfortable and ergonomic office chair.",
                         qty: 40,
                         weight: "10kg",
                         size: "8kg",
                         dimension: "20",
                         standard_price: "90",
                         discount: {
                              amount: "10",
                              type: "flat",
                              start_date: "02/12/2024",
                              end_date: "02/12/2025",
                              discountedAmount: "90",
                         },
                         company_id,
                         product_tag_ids: ["654"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 38,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "furniture" }, { name: "supplies" }, { name: "electronics" }],
          },
          "Art & Craft": {
               products: [
                    {
                         name: "Acrylic Paint Set",
                         category_id: "269",
                         uom_name: "1",
                         published: true,
                         list_price: "40.00",
                         public_categ: "Art & Craft",
                         description: "A set of vibrant acrylic paints for artists.",
                         qty: 100,
                         weight: "1kg",
                         size: "0.8kg",
                         dimension: "5",
                         standard_price: "35",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "01/01/2025",
                              end_date: "01/01/2026",
                              discountedAmount: "35",
                         },
                         company_id,
                         product_tag_ids: ["321"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 95,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Sketchbook",
                         category_id: "269",
                         uom_name: "1",
                         published: true,
                         list_price: "15.00",
                         public_categ: "Art & Craft",
                         description: "A high-quality sketchbook for drawing and sketching.",
                         qty: 150,
                         weight: "0.5kg",
                         size: "0.4kg",
                         dimension: "3",
                         standard_price: "13",
                         discount: {
                              amount: "2",
                              type: "flat",
                              start_date: "02/01/2025",
                              end_date: "02/01/2026",
                              discountedAmount: "13",
                         },
                         company_id,
                         product_tag_ids: ["654"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 145,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "paints" }, { name: "papers" }, { name: "tools" }],
          },
          "Travel & Hospitality": {
               products: [
                    {
                         name: "Suitcase",
                         category_id: "270",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "Travel & Hospitality",
                         description: "A durable suitcase for all your travel needs.",
                         qty: 80,
                         weight: "4kg",
                         size: "3.5kg",
                         dimension: "20",
                         standard_price: "90",
                         discount: {
                              amount: "10",
                              type: "flat",
                              start_date: "01/02/2025",
                              end_date: "01/02/2026",
                              discountedAmount: "90",
                         },
                         company_id,
                         product_tag_ids: ["321"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 75,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Travel Pillow",
                         category_id: "270",
                         uom_name: "1",
                         published: true,
                         list_price: "20.00",
                         public_categ: "Travel & Hospitality",
                         description: "A comfortable travel pillow for long journeys.",
                         qty: 120,
                         weight: "0.3kg",
                         size: "0.2kg",
                         dimension: "5",
                         standard_price: "18",
                         discount: {
                              amount: "2",
                              type: "flat",
                              start_date: "02/02/2025",
                              end_date: "02/02/2026",
                              discountedAmount: "18",
                         },
                         company_id,
                         product_tag_ids: ["654"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 115,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "luggage" }, { name: "accessories" }, { name: "comfort" }],
          },
          Education: {
               products: [
                    {
                         name: "Textbook",
                         category_id: "271",
                         uom_name: "1",
                         published: true,
                         list_price: "60.00",
                         public_categ: "Education",
                         description: "A comprehensive textbook for students.",
                         qty: 150,
                         weight: "1kg",
                         size: "0.8kg",
                         dimension: "5",
                         standard_price: "55",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "01/03/2025",
                              end_date: "01/03/2026",
                              discountedAmount: "55",
                         },
                         company_id,
                         product_tag_ids: ["321"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 145,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "Scientific Calculator",
                         category_id: "271",
                         uom_name: "1",
                         published: true,
                         list_price: "25.00",
                         public_categ: "Education",
                         description: "A scientific calculator for solving complex problems.",
                         qty: 200,
                         weight: "0.2kg",
                         size: "0.15kg",
                         dimension: "3",
                         standard_price: "20",
                         discount: {
                              amount: "5",
                              type: "flat",
                              start_date: "02/03/2025",
                              end_date: "02/03/2026",
                              discountedAmount: "20",
                         },
                         company_id,
                         product_tag_ids: ["654"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 190,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-3.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-4.jpg",
                         ]),
                    },
               ],
               categories: [{ name: "books" }, { name: "calculators" }, { name: "supplies" }],
          },
     };

     const fallbackProducts = (category) => [
          {
               name: "Fallback Product 1",
               category_id: "1",
               uom_name: "1",
               published: true,
               list_price: "100.00",
               public_categ: category,
               description: "This is a fallback product.",
               qty: 40,
               weight: "1kg",
               size: "0.5kg",
               images: JSON.stringify([
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
               ]),
               dimension: "3",
               standard_price: "500",
               discount: {
                    amount: "200",
                    type: "",
                    start_date: "12/10/2024",
                    end_date: "12/10/2025",
                    discountedAmount: "300",
               },
               company_id,
               product_tag_ids: ["123"],
               x_variants: false,
               free_shipping: true,
               x_shipping_package: {
                    weight: { value: 0, unit: "ounce" },
                    dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                    material: "",
                    type: "",
                    fragile: false,
                    handlingInstructions: "",
               },
               x_show_sold_count: true,
               x_featured_product: true,
               x_total_available_qty: 39,
               x_inventory_tracking: true,
          },
          {
               name: "Fallback Product 2",
               category_id: "1",
               uom_name: "1",
               published: true,
               list_price: "100.00",
               public_categ: category,
               description: "This is a fallback product.",
               qty: 40,
               weight: "1kg",
               size: "0.5kg",
               images: JSON.stringify([
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
               ]),
               dimension: "3",
               standard_price: "500",
               discount: {
                    amount: "200",
                    type: "",
                    start_date: "12/10/2024",
                    end_date: "12/10/2025",
                    discountedAmount: "300",
               },
               company_id,
               product_tag_ids: ["123"],
               x_variants: false,
               free_shipping: true,
               x_shipping_package: {
                    weight: { value: 0, unit: "ounce" },
                    dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                    material: "",
                    type: "",
                    fragile: false,
                    handlingInstructions: "",
               },
               x_show_sold_count: true,
               x_featured_product: true,
               x_total_available_qty: 39,
               x_inventory_tracking: true,
          },
          {
               name: "Fallback Product 3",
               category_id: "1",
               uom_name: "1",
               published: true,
               list_price: "100.00",
               public_categ: category,
               description: "This is a fallback product.",
               qty: 40,
               weight: "1kg",
               size: "0.5kg",
               images: JSON.stringify([
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
               ]),
               dimension: "3",
               standard_price: "500",
               discount: {
                    amount: "200",
                    type: "",
                    start_date: "12/10/2024",
                    end_date: "12/10/2025",
                    discountedAmount: "300",
               },
               company_id,
               product_tag_ids: ["123"],
               x_variants: false,
               free_shipping: true,
               x_shipping_package: {
                    weight: { value: 0, unit: "ounce" },
                    dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                    material: "",
                    type: "",
                    fragile: false,
                    handlingInstructions: "",
               },
               x_show_sold_count: true,
               x_featured_product: true,
               x_total_available_qty: 39,
               x_inventory_tracking: true,
          },
          {
               name: "Fallback Product 4",
               category_id: "1",
               uom_name: "1",
               published: true,
               list_price: "100.00",
               public_categ: category,
               description: "This is a fallback product.",
               qty: 40,
               weight: "1kg",
               size: "0.5kg",
               images: JSON.stringify([
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
               ]),
               dimension: "3",
               standard_price: "500",
               discount: {
                    amount: "200",
                    type: "",
                    start_date: "12/10/2024",
                    end_date: "12/10/2025",
                    discountedAmount: "300",
               },
               company_id,
               product_tag_ids: ["123"],
               x_variants: false,
               free_shipping: true,
               x_shipping_package: {
                    weight: { value: 0, unit: "ounce" },
                    dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                    material: "",
                    type: "",
                    fragile: false,
                    handlingInstructions: "",
               },
               x_show_sold_count: true,
               x_featured_product: true,
               x_total_available_qty: 39,
               x_inventory_tracking: true,
          },
     ];

     const selectedProducts = categ_ids
          .map((category) => ProductByCateg[category] || { products: fallbackProducts(category) })
          .flat();

     return selectedProducts;
};
