exports.initProducts = (company_id, categ_ids) => {
     const ProductByCateg = {
          "Books and Media": {
               products: [
                    {
                         name: "1984",
                         category_id: "2",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "booking",
                         description:
                              "A dystopian social science fiction novel and cautionary tale, written by the English writer George Orwell.",
                         qty: 40,
                         weight: "1kg",
                         size: "0.5kg",

                         dimension: "3",
                         standard_price: "500",
                         discount: {
                              amount: "200",
                              type: "",
                              start_date: "12/10/2024",
                              end_date: "12/10/2025",
                              discountedAmount: "300",
                         },
                         company_id,
                         product_tag_ids: ["123"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 39,
                         x_inventory_tracking: true,
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                    },
                    {
                         name: "To Kill a Mockingbird",
                         category_id: "2",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "booking",
                         description:
                              "A novel by Harper Lee published in 1960. Instantly successful, widely read in high schools and middle schools in the United States.",
                         qty: 40,
                         weight: "1kg",
                         size: "0.5kg",
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                         dimension: "3",
                         standard_price: "500",
                         discount: {
                              amount: "200",
                              type: "",
                              start_date: "12/10/2024",
                              end_date: "12/10/2025",
                              discountedAmount: "300",
                         },
                         company_id,
                         product_tag_ids: ["123"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 39,
                         x_inventory_tracking: true,
                    },
                    {
                         name: "The Great Gatsby",
                         category_id: "2",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "booking",
                         description:
                              "A 1925 novel written by American author F. Scott Fitzgerald that follows a cast of characters living in the fictional towns of West Egg and East Egg.",
                         qty: 40,
                         weight: "1kg",
                         size: "0.5kg",
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                         dimension: "3",
                         standard_price: "500",
                         discount: {
                              amount: "200",
                              type: "",
                              start_date: "12/10/2024",
                              end_date: "12/10/2025",
                              discountedAmount: "300",
                         },
                         company_id,
                         product_tag_ids: ["123"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 39,
                         x_inventory_tracking: true,
                    },
                    {
                         name: "Pride and Prejudice",
                         category_id: "2",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "booking",
                         description: "A romantic novel of manners written by Jane Austen in 1813.",
                         qty: 40,
                         weight: "1kg",
                         size: "0.5kg",
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                         dimension: "3",
                         standard_price: "500",
                         discount: {
                              amount: "200",
                              type: "",
                              start_date: "12/10/2024",
                              end_date: "12/10/2025",
                              discountedAmount: "300",
                         },
                         company_id,
                         product_tag_ids: ["123"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 39,
                         x_inventory_tracking: true,
                    },
                    {
                         name: "The Catcher in the Rye",
                         category_id: "2",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "booking",
                         description:
                              "A novel by J. D. Salinger, partially published in serial form in 1945–1946 and as a novel in 1951.",
                         qty: 40,
                         weight: "1kg",
                         size: "0.5kg",
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                         dimension: "3",
                         standard_price: "500",
                         discount: {
                              amount: "200",
                              type: "",
                              start_date: "12/10/2024",
                              end_date: "12/10/2025",
                              discountedAmount: "300",
                         },
                         company_id,
                         product_tag_ids: ["123"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 39,
                         x_inventory_tracking: true,
                    },
                    {
                         name: "Moby-Dick",
                         category_id: "2",
                         uom_name: "1",
                         published: true,
                         list_price: "100.00",
                         public_categ: "booking",
                         description:
                              "An 1851 novel by Herman Melville. The book is the sailor Ishmael’s narrative of the obsessive quest of Ahab, captain of the whaling ship Pequod.",
                         qty: 40,
                         weight: "1kg",
                         size: "0.5kg",
                         images: JSON.stringify([
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                              "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
                         ]),
                         dimension: "3",
                         standard_price: "500",
                         discount: {
                              amount: "200",
                              type: "",
                              start_date: "12/10/2024",
                              end_date: "12/10/2025",
                              discountedAmount: "300",
                         },
                         company_id,
                         product_tag_ids: ["123"],
                         x_variants: false,
                         free_shipping: true,
                         x_shipping_package: {
                              weight: { value: 0, unit: "ounce" },
                              dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                              material: "",
                              type: "",
                              fragile: false,
                              handlingInstructions: "",
                         },
                         x_show_sold_count: true,
                         x_featured_product: true,
                         x_total_available_qty: 39,
                         x_inventory_tracking: true,
                    },
               ],
               categories: [{ name: "fiction" }, { name: "thriller" }, { name: "romance" }],
          },
     };

     const fallbackProducts = [
          {
               name: "Fallback Product 1",
               category_id: "1",
               uom_name: "1",
               published: true,
               list_price: "100.00",
               public_categ: "booking",
               description: "This is a fallback product.",
               qty: 40,
               weight: "1kg",
               size: "0.5kg",
               images: JSON.stringify([
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
               ]),
               dimension: "3",
               standard_price: "500",
               discount: {
                    amount: "200",
                    type: "",
                    start_date: "12/10/2024",
                    end_date: "12/10/2025",
                    discountedAmount: "300",
               },
               company_id,
               product_tag_ids: ["123"],
               x_variants: false,
               free_shipping: true,
               x_shipping_package: {
                    weight: { value: 0, unit: "ounce" },
                    dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                    material: "",
                    type: "",
                    fragile: false,
                    handlingInstructions: "",
               },
               x_show_sold_count: true,
               x_featured_product: true,
               x_total_available_qty: 39,
               x_inventory_tracking: true,
          },
          {
               name: "Fallback Product 2",
               category_id: "1",
               uom_name: "1",
               published: true,
               list_price: "100.00",
               public_categ: "booking",
               description: "This is a fallback product.",
               qty: 40,
               weight: "1kg",
               size: "0.5kg",
               images: JSON.stringify([
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
               ]),
               dimension: "3",
               standard_price: "500",
               discount: {
                    amount: "200",
                    type: "",
                    start_date: "12/10/2024",
                    end_date: "12/10/2025",
                    discountedAmount: "300",
               },
               company_id,
               product_tag_ids: ["123"],
               x_variants: false,
               free_shipping: true,
               x_shipping_package: {
                    weight: { value: 0, unit: "ounce" },
                    dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                    material: "",
                    type: "",
                    fragile: false,
                    handlingInstructions: "",
               },
               x_show_sold_count: true,
               x_featured_product: true,
               x_total_available_qty: 39,
               x_inventory_tracking: true,
          },
          {
               name: "Fallback Product 3",
               category_id: "1",
               uom_name: "1",
               published: true,
               list_price: "100.00",
               public_categ: "booking",
               description: "This is a fallback product.",
               qty: 40,
               weight: "1kg",
               size: "0.5kg",
               images: JSON.stringify([
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
               ]),
               dimension: "3",
               standard_price: "500",
               discount: {
                    amount: "200",
                    type: "",
                    start_date: "12/10/2024",
                    end_date: "12/10/2025",
                    discountedAmount: "300",
               },
               company_id,
               product_tag_ids: ["123"],
               x_variants: false,
               free_shipping: true,
               x_shipping_package: {
                    weight: { value: 0, unit: "ounce" },
                    dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                    material: "",
                    type: "",
                    fragile: false,
                    handlingInstructions: "",
               },
               x_show_sold_count: true,
               x_featured_product: true,
               x_total_available_qty: 39,
               x_inventory_tracking: true,
          },
          {
               name: "Fallback Product 4",
               category_id: "1",
               uom_name: "1",
               published: true,
               list_price: "100.00",
               public_categ: "booking",
               description: "This is a fallback product.",
               qty: 40,
               weight: "1kg",
               size: "0.5kg",
               images: JSON.stringify([
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-1.jpg",
                    "https://absa7kzimnaf.blob.core.windows.net/templates-images/all-template-product/product-2.jpg",
               ]),
               dimension: "3",
               standard_price: "500",
               discount: {
                    amount: "200",
                    type: "",
                    start_date: "12/10/2024",
                    end_date: "12/10/2025",
                    discountedAmount: "300",
               },
               company_id,
               product_tag_ids: ["123"],
               x_variants: false,
               free_shipping: true,
               x_shipping_package: {
                    weight: { value: 0, unit: "ounce" },
                    dimensions: { length: 0, width: 0, height: 0, unit: "cm" },
                    material: "",
                    type: "",
                    fragile: false,
                    handlingInstructions: "",
               },
               x_show_sold_count: true,
               x_featured_product: true,
               x_total_available_qty: 39,
               x_inventory_tracking: true,
          },
     ];

     const selectedProducts = categ_ids
          .map((category) => ProductByCateg[category] || { products: fallbackProducts })
          .flat();

     return selectedProducts;
};
