const bannerImages = require("./bannerImages");

const midBannerConfig = {
     theme2: [
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 700,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 700,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 700,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 300,
               height: 700,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
     ],
     theme5: [
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme5"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme5"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme5"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
     ],
     theme6: [
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme6"]?.banner1,
               link: "/",
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme6"]?.banner1,
               link: "/",
          },
     ],
     theme12: [
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme12"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme12"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme12"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme12"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme12"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
     ],
     theme17: [
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme17"]?.banner1,
               link: "/",
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme17"]?.banner1,
               link: "/",
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme17"]?.banner1,
               link: "/",
          },
     ],
     theme21: [
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme21"]?.banner1,
               link: "/",
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme21"]?.banner1,
               link: "/",
          },
     ],
     theme13: [
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme13"]?.banner1,
               link: "/",
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme13"]?.banner1,
               link: "/",
          },
     ],
};

module.exports = midBannerConfig;
