const bannerImages = require("./bannerImages");

const midBannerConfig = {
     theme2: [
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 700,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 700,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 700,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 300,
               height: 700,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme2"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
     ],
     theme5: [
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme5"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme5"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
          {
               title: "",
               text: "",
               imageUrl: bannerImages?.["theme5"]?.banner1,
               link: "/",
               width: 300,
               height: 400,
          },
     ],
};

module.exports = midBannerConfig;
